In [ ]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv("Retail_Dataset_Cleaned.csv")
retail

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [4]:
retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
dtypes: float64(15), int64(10), str(22)
memory usage: 1.8 MB

In [5]:
retail.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [6]:
retail.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [7]:
retail.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [8]:
retail.groupby('City')['Revenue'].sum()

City
Ahmedabad        2.655276e+08
Bangalore        8.407997e+08
Bhopal           1.079895e+08
Chennai          7.419116e+08
Delhi            1.661122e+09
Hyderabad        6.597958e+08
Jaipur           2.670945e+08
Kanpur           8.430218e+07
Lucknow          9.486221e+07
Mumbai           1.674840e+09
Nagpur           7.479879e+07
Pune             2.936829e+08
Surat            2.340634e+08
Visakhapatnam    8.106636e+07
Name: Revenue, dtype: float64

In [10]:
category_rev = pd.pivot_table(
    retail,
    values= "Revenue",
    index= "Category",
    aggfunc="sum"
)

In [11]:
category_rev

                      Revenue
Category
Clothes          2.220630e+08
Electronics      3.623063e+09
Gadgets          2.654379e+09
Groceries        2.394028e+07
Home Appliances  5.584119e+08

In [14]:
city_rev = pd.pivot_table(
    retail,
    values= "Revenue",
    index= "City",
    aggfunc="sum"
)

In [15]:
city_rev

                    Revenue
City
Ahmedabad      2.655276e+08
Bangalore      8.407997e+08
Bhopal         1.079895e+08
Chennai        7.419116e+08
Delhi          1.661122e+09
Hyderabad      6.597958e+08
Jaipur         2.670945e+08
Kanpur         8.430218e+07
Lucknow        9.486221e+07
Mumbai         1.674840e+09
Nagpur         7.479879e+07
Pune           2.936829e+08
Surat          2.340634e+08
Visakhapatnam  8.106636e+07

In [16]:
segment_rev = pd.pivot_table(
    retail,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_rev

                       Revenue
Customer_Segment
Budget            1.712615e+09
Luxury            1.863606e+09
Mid-Range         1.822548e+09
Premium           1.683088e+09

In [21]:
category_summary = pd.pivot_table(
    retail,
    values= "Revenue",
    index= "Category",
    aggfunc=["sum", "count", "mean", "max", "min"]
)

category_summary

                          sum   count          mean         max       min
                      Revenue Revenue       Revenue     Revenue   Revenue
Category
Clothes          2.220630e+08    1293  1.717425e+05   1245972.0    4985.0
Electronics      3.623063e+09    1308  2.769926e+06  11182353.0  120655.0
Gadgets          2.654379e+09    1023  2.594701e+06  23343582.0    9295.0
Groceries        2.394028e+07    1012  2.365641e+04    350176.0     840.0
Home Appliances  5.584119e+08     510  1.094925e+06   6588592.0   81333.0

In [24]:
city_performance = pd.pivot_table(
    retail,
    values=["Revenue", "Profit_Margin"],
    index= "City",
    aggfunc={
        "Revenue" : "sum",
        "Profit_Margin" : "mean"
    })

In [25]:
city_performance

               Profit_Margin       Revenue
City
Ahmedabad          22.624845  2.655276e+08
Bangalore          22.830374  8.407997e+08
Bhopal             22.620614  1.079895e+08
Chennai            22.259758  7.419116e+08
Delhi              22.282928  1.661122e+09
Hyderabad          22.239853  6.597958e+08
Jaipur             22.326377  2.670945e+08
Kanpur             22.539515  8.430218e+07
Lucknow            22.070538  9.486221e+07
Mumbai             22.435763  1.674840e+09
Nagpur             22.342162  7.479879e+07
Pune               22.756934  2.936829e+08
Surat              22.883691  2.340634e+08
Visakhapatnam      22.574245  8.106636e+07

In [26]:
retail.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [29]:
city_performance_summary = pd.pivot_table(
    retail,
    values=["Revenue", "Profit_Margin", "Brand_Awareness", "Brand_Loyalty", "Category", "Sub_Category"],
    index= "City",
    aggfunc={
        "Revenue" : "sum",
        "Profit_Margin" : "mean",
        "Brand_Awareness" : "mean",
        "Brand_Loyalty" : "mean",
        "Category" : "count",
        "Sub_Category" : "count"

    })

In [30]:
city_performance_summary

,Brand_Awareness,Brand_Loyalty,Category,Profit_Margin,Revenue,Sub_Category
City,,,,,,
Ahmedabad,77.978682,75.319380,258,22.624845,2.655276e+08,258
Bangalore,85.190354,84.052165,508,22.830374,8.407997e+08,508
Bhopal,65.055263,75.357018,114,22.620614,1.079895e+08,114
Chennai,85.097782,84.036694,496,22.259758,7.419116e+08,496
Delhi,84.939438,83.772257,1103,22.282928,1.661122e+09,1103
Hyderabad,85.129895,83.831158,475,22.239853,6.597958e+08,475
Jaipur,65.009783,75.507246,276,22.326377,2.670945e+08,276
Kanpur,65.353398,75.785437,103,22.539515,8.430218e+07,103
Lucknow,65.206452,75.467742,93,22.070538,9.486221e+07,93
Mumbai,85.131627,83.652108,996,22.435763,1.674840e+09,996
Nagpur,64.681982,75.569369,111,22.342162,7.479879e+07,111
Pune,78.103650,75.877737,274,22.756934,2.936829e+08,274
Surat,64.642060,76.142918,233,22.883691,2.340634e+08,233
Visakhapatnam,65.089623,76.001887,106,22.574245,8.106636e+07,106