In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv("movies - movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [4]:
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [5]:
movies.tail(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [6]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

In [7]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

In [8]:
ipl = pd.read_csv("ipl-matches - ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [9]:
student_data = [
    [100, 80, 10],
    [90, 0, 7],
    [120, 100, 14],
    [80, 50, 2]
]

pd.DataFrame(student_data, columns=['iq', 'marks', 'package'])

    iq  marks  package
0  100     80       10
1   90      0        7
2  120    100       14
3   80     50        2

In [10]:
student_dict = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students.set_index('name', inplace=True)
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [11]:
rd = pd.read_csv("Retail_Dataset_Modified.csv")
rd

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [12]:
rd.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [13]:
rd.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [14]:
rd.sample(5)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
550,BX_MUMBAI_026,BrandX_India Gadget Zone Mumbai,BrandX_India,Mall Store,Mumbai,Metro,Samsung Galaxy S23,Electronics,Smartphones,Declining,...,84.0,88.7,Aggressive,Low,7.0,258,5,2022,Q2,Summer
5137,BX_SURAT_009,BrandX_India Trends Surat,BrandX_India,Express,Surat,Tier2,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,72.3,60.1,Standard,Medium,4.0,53,9,2023,Q3,Monsoon
2135,BX_PUNE_030,BrandX_India Mobile Pune,BrandX_India,Express,Pune,Tier1,Bose SoundLink,Gadgets,Bluetooth Speakers,Growing,...,85.1,82.9,Standard,Low,5.0,125,4,2023,Q2,Summer
2789,BX_SURAT_036,BrandX_India Daily Surat,BrandX_India,Street Store,Surat,Tier2,Sunflower Oil 1L,Groceries,Oil,Growing,...,69.3,63.5,Standard,Low,3.0,107,8,2023,Q3,Monsoon
1236,BX_DELHI_065,BrandX_India Gadget Zone Delhi,BrandX_India,Flagship,Delhi,Metro,OnePlus 11,Electronics,Smartphones,Mature,...,80.6,81.3,Competitive,Low,1.0,211,10,2022,Q4,Winter

In [15]:
print("Columns in Dataset:")
print(rd.columns)

Columns in Dataset:
Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [16]:
print("Data Types:")
print(rd.dtypes)

Data Types:
Store_ID                     str
Store_Name                   str
Brand_Name                   str
Store_Type                   str
City                         str
City_Tier                    str
Product_Name                 str
Category                     str
Sub_Category                 str
Product_Stage                str
Quantity_Available           str
Units_Sold                   str
Unit_Price                 int64
Cost_Price                 int64
Revenue                      str
Profit_Margin            float64
Average_Order_Value        int64
Inventory_Turnover       float64
Days_of_Stock              int64
Customer_Segment             str
Sales_Channel                str
Payment_Method               str
Supplier                     str
Supplier_Rating              str
Promotion_Type               str
Promotion_Impact         float64
Max_Discount_Offered       int64
Return_Rate              float64
Return_Reason                str
Customer_Satisfaction    float64
Online_Rating            float64
Review_Count               int64
Sales_Rep_Experience       int64
Sales_Rep_Rating         float64
Market_Share             float64
Competition_Level            str
Competitor_Count           int64
Brand_Loyalty            float64
Brand_Awareness          float64
Price_Competitiveness        str
Weather_Impact               str
Delivery_Time            float64
Shipping_Cost                str
Month                      int64
Year                       int64
Quarter                      str
Season                       str
dtype: object

In [17]:
rd.info()

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB

In [18]:
print(rd.describe())

          Unit_Price     Cost_Price  Profit_Margin  Average_Order_Value  \
count    5171.000000    5171.000000    5171.000000          5171.000000
mean    36147.283117   28008.718236      22.455080         45000.251789
std     53910.395954   41848.286241       4.349469         67405.809814
min        36.000000      28.000000      14.680000            41.000000
25%      2016.500000    1548.500000      18.675000          2476.000000
50%     11816.000000    9136.000000      22.450000         14734.000000
75%     53778.500000   41569.000000      26.235000         66630.000000
max    307651.000000  252171.000000      30.430000        450890.000000

       Inventory_Turnover  Days_of_Stock  Promotion_Impact  \
count         5171.000000    5171.000000       5171.000000
mean             3.928517     142.718816         20.979791
std              2.284159     128.281114         12.212204
min              0.300000      32.000000          0.000000
25%              2.220000      68.000000         13.100000
50%              3.440000     105.000000         22.300000
75%              5.260000     162.000000         31.200000
max             11.100000    1200.000000         40.000000

       Max_Discount_Offered  Return_Rate  Customer_Satisfaction  ...  \
count           5171.000000  5171.000000            5094.000000  ...
mean              22.679172     4.018294               4.209109  ...
std               15.784690     2.292903               0.280465  ...
min                0.000000     0.000000               3.600000  ...
25%                9.000000     2.000000               4.000000  ...
50%               22.000000     4.100000               4.200000  ...
75%               36.000000     6.000000               4.400000  ...
max               50.000000     8.000000               4.900000  ...

       Review_Count  Sales_Rep_Experience  Sales_Rep_Rating  Market_Share  \
count   5171.000000           5171.000000       5171.000000   5171.000000
mean     256.498936              5.548250          4.248018     15.406556
std      140.948535              2.861696          0.433274      6.009766
min       10.000000              1.000000          3.500000      3.000000
25%      138.000000              3.000000          3.900000     11.300000
50%      256.000000              6.000000          4.200000     14.900000
75%      378.000000              8.000000          4.600000     18.900000
max      500.000000             10.000000          5.000000     30.000000

       Competitor_Count  Brand_Loyalty  Brand_Awareness  Delivery_Time  \
count       5171.000000    5171.000000      5171.000000    5111.000000
mean          16.231483      81.351228        80.307097       3.984934
std            6.646939       8.018098         8.542352       2.021598
min            3.000000      67.000000        60.000000       1.000000
25%           11.000000      75.900000        77.700000       2.000000
50%           18.000000      80.400000        83.000000       4.000000
75%           22.000000      84.600000        86.600000       6.000000
max           25.000000     100.000000        90.000000       7.000000

             Month         Year
count  5171.000000  5171.000000
mean      6.567588  2023.016438
std       3.463351     0.814235
min       1.000000  2022.000000
25%       4.000000  2022.000000
50%       7.000000  2023.000000
75%      10.000000  2024.000000
max      12.000000  2024.000000

[8 rows x 21 columns]

In [19]:
print("Missing Values:")
print(rd.isnull().sum())

Missing Values:
Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [20]:
print(rd['Category'].unique())

<StringArray>
[          'Groceries',             'Clothes',             'Gadgets',
         'Electronics',     'Home Appliances',         'ELECTRONICS',
       '  Groceries  ',     'home appliances',     'HOME APPLIANCES',
     '  Electronics  ',             'gadgets',           'groceries',
         'electronics', '  Home Appliances  ',             'clothes',
         '  Gadgets  ',           'GROCERIES',         '  Clothes  ',
             'GADGETS',             'CLOTHES']
Length: 20, dtype: str

In [21]:
print(rd['Category'].value_counts())

Category
Electronics            1295
Clothes                1290
Gadgets                1017
Groceries              1006
Home Appliances         503
  Electronics             8
electronics               6
CLOTHES                   5
ELECTRONICS               4
HOME APPLIANCES           4
gadgets                   4
groceries                 4
GROCERIES                 4
  Groceries               3
home appliances           3
  Home Appliances         3
clothes                   3
  Gadgets                 3
  Clothes                 3
GADGETS                   3
Name: count, dtype: int64

In [22]:
selected_columns = rd[['Revenue',
                        'Units_Sold',
                        'Profit_Margin']]

print(selected_columns.head())

   Revenue Units_Sold  Profit_Margin
0     7320         24          21.64
1     1645         35          29.79
2    66340         31          19.86
3    77748         22          18.11
4  1976364         39          20.15

In [23]:
print(rd.iloc[0])

Store_ID                                  BX_PUNE_034
Store_Name               BrandX_India Superstore Pune
Brand_Name                               BrandX_India
Store_Type                                   Flagship
City                                             Pune
City_Tier                                       Tier1
Product_Name                           Green Tea 100g
Category                                    Groceries
Sub_Category                                      Tea
Product_Stage                               Declining
Quantity_Available                                125
Units_Sold                                         24
Unit_Price                                        305
Cost_Price                                        239
Revenue                                          7320
Profit_Margin                                   21.64
Average_Order_Value                               432
Inventory_Turnover                                2.3
Days_of_Stock                                     156
Customer_Segment                               Budget
Sales_Channel                     BrandX_India Online
Payment_Method                                    UPI
Supplier                  BrandX_India E-commerce Hub
Supplier_Rating                                   Nan
Promotion_Type                         Festival Offer
Promotion_Impact                                 23.1
Max_Discount_Offered                                9
Return_Rate                                       3.1
Return_Reason                              Wrong Size
Customer_Satisfaction                             4.0
Online_Rating                                     4.6
Review_Count                                       53
Sales_Rep_Experience                                5
Sales_Rep_Rating                                  4.8
Market_Share                                     15.3
Competition_Level                              Medium
Competitor_Count                                    8
Brand_Loyalty                                    70.8
Brand_Awareness                                  75.7
Price_Competitiveness                        Standard
Weather_Impact                                    Low
Delivery_Time                                     6.0
Shipping_Cost                                      57
Month                                               1
Year                                             2022
Quarter                                            Q1
Season                                         Spring
Name: 0, dtype: object

In [24]:
print("Dataset Shape:")
print(rd.shape)

Dataset Shape:
(5171, 47)

In [25]:
students.loc['ankit'::2]

         iq  marks  package
name
ankit    90     70        7
rishabh  80     50        2
ankita    0      0        0

In [26]:
students.loc[["ankit", "rishabh", "ankita"]]

         iq  marks  package
name
ankit    90     70        7
rishabh  80     50        2
ankita    0      0        0

Task 2

In [36]:
high_price = rd[rd['Unit_Price']>1000]
high_price[['Store_Name', 'Brand_Name', 'Category']].head()

                        Store_Name    Brand_Name     Category
2         BrandX_India Trends Pune  BrandX_India      Clothes
3      BrandX_India Trends Chennai  BrandX_India      Clothes
4     BrandX_India Connect Chennai  BrandX_India      Gadgets
6  BrandX_India Accessories Mumbai  BrandX_India      Gadgets
7       BrandX_India Digital Delhi  BrandX_India  Electronics

In [37]:
low_price = rd[rd['Unit_Price']<500]
low_price[['Product_Name', 'Category', 'Unit_Price']].head()

        Product_Name   Category  Unit_Price
0     Green Tea 100g  Groceries         305
1    White Sugar 1kg  Groceries          47
5       Toor Dal 1kg  Groceries         173
11   Olive Oil 500ml  Groceries         377
17  Sunflower Oil 1L  Groceries         173

In [31]:
medium_price = rd[
    (rd['Unit_Price'] >= 500) &
    (rd['Unit_Price'] <= 1500)
]

medium_price[['Product_Name', 'Category', 'Unit_Price']].head()

        Product_Name   Category  Unit_Price
9     H&M Cotton Tee    Clothes         808
21  Basmati Rice 5kg  Groceries         659
38    H&M Cotton Tee    Clothes        1015
43    H&M Cotton Tee    Clothes        1269
44    H&M Cotton Tee    Clothes        1059

In [33]:
sorted_price = rd.sort_values(
    by = 'Unit_Price',
    ascending=False
)
sorted_price[['Product_Name', 'Category', 'Unit_Price']].head()

          Product_Name Category  Unit_Price
2458  Sony Alpha a7 IV  Gadgets      307651
4584  Sony Alpha a7 IV  Gadgets      306035
4765  Sony Alpha a7 IV  Gadgets      305722
1099  Sony Alpha a7 IV  Gadgets      305634
2820  Sony Alpha a7 IV  Gadgets      305536

In [35]:
top_price = rd.nlargest(10, 'Unit_Price')
print(top_price[['Unit_Price']])

      Unit_Price
2458      307651
4584      306035
4765      305722
1099      305634
2820      305536
2134      304378
3658      304251
3880      303095
718       302841
1065      302473

In [38]:
print("Number of Products with Unit Price > 1000:")
print(len(high_price))

Number of Products with Unit Price > 1000:
4127